Repository couchbase/sync_gateway, pull requests merged in 2018-02, with the labels that each got.

#3282 #3255 Add recover in blipHandler sendRevision goroutine
  manifest/default.xml
  rest/blip_sync.go
Labels: in progress, review

#3290 #3279 BLIP: proposeChanges conflict free mode
  db/attachment_test.go
  db/changes_test.go
  db/crud.go
  db/crud_test.go
  db/database_test.go
  db/shadower_test.go
  rest/blip_api_test.go
  rest/blip_sync.go
  rest/bulk_api.go
  rest/doc_api.go
  rest/utilities_testing.go
Labels: in progress, review

#3293 Disable TestChangesIncludeDocs for compatibility test
  rest/changes_api_test.go
Labels: in progress, review

#3287 Feature/issue 3283 repl invalid seq
  base/util.go
  base/util_test.go
  db/sequence_id.go
  rest/blip_sync.go
  rest/blip_sync_messages.go
  rest/blip_sync_messages_test.go
  rest/handler.go
  rest/utilities_testing.go
Labels: in progress, review

#3299 Fixes #3298 - Rework ServerContext PostStartup logic
  base/util.go
  rest/config.go
  rest/config_test.go
  rest/server_context.go
Labels: in progress, review

#3289 Add benchmark for GET w/ 100% rev cache miss
  rest/api_benchmark_test.go
Labels: review

#3302 Fixes #3300 - Re-add PIDFILE to startup scripts
  service/sg_accel_service_install.sh
  service/sg_accel_service_uninstall.sh
  service/sg_accel_service_upgrade.sh
  service/sync_gateway_service_install.sh
  service/sync_gateway_service_uninstall.sh
  service/sync_gateway_service_upgrade.sh
Labels: in progress

#3303 Restores TestChangesIncludeDocs
  rest/changes_api_test.go
Labels: review

#3253 Document caveat when cross-compiling Sync Gateway to Linux
  docs/BUILD.md
Labels: in progress, review

#3316 Fixes #3307: Pushing yet-unseen tombstoned doc to Sync Gateway returns error in XATTR mode
  base/bucket_gocb.go
  base/bucket_gocb_test.go
  rest/api_test.go
Labels: review

#3318 Point to latest go-blip
  manifest/default.xml
Labels: in progress

#3317 Support running generateChanges in one-shot mode
  base/logging.go
  db/change_cache_test.go
  rest/api_test.go
  rest/blip_api_test.go
  rest/blip_sync.go
  rest/changes_api.go
  rest/import_test.go
  test.sh
Labels: in progress

#3328 Skip disabled tests for improved visiblity and allow test suite to run offline
  db/change_cache_test.go
  db/database_test.go
  db/kv_dense_channel_storage_test.go
  rest/api_test.go
  rest/changes_api_test.go
  rest/import_test.go
  rest/login_test.go
  rest/view_api_test.go
Labels: review

#3304 Feature/issue 3281 blip handler cant get doc
  db/crud.go
  rest/blip_api_test.go
  rest/utilities_testing.go
Labels: review

#3336 Remove unnecessary backfill status condition
  base/dcp_feed.go
Labels: in progress

#3325 Uptake go-blip change: Update WebSocket protocol to “BLIP_3"
  manifest/default.xml
  rest/blip_sync.go
  rest/utilities_testing.go
Labels: review

#3331 Fix json struct tag on DocAttachment
  db/attachment.go
Labels: in progress, review

#3338 Example of stripping header lines from pprof
  tools/README.adoc
Labels: review

#3342 Only add the _deleted property to incoming documents when true
  rest/blip_api_test.go
  rest/blip_sync.go
Labels: review

#3343 Wait for sequence in TestSkippedViewRetrieval
  db/change_cache_test.go
Labels: in progress, review

#3326 #3229 Rework sg-replicate startup
  base/replicator.go
  base/replicator_test.go
  rest/server_context.go
Labels: in progress, review

#3308 #3295 - Add log redaction infrastructure
  base/logging.go
  base/logging_test.go
  base/redactor.go
  base/redactor_test.go
  base/redactor_userdata.go
  base/redactor_userdata_test.go
Labels: review

#3340 Disable TestRepairBucketRevTreeCycles and add TODO
  db/repair_bucket.go
  db/repair_bucket_test.go
Labels: in progress, review
