Repository couchbase/sync_gateway, pull requests merged in 2018-06, with the labels that each got.

#3619 Fix LoggingBucket always using TAP feed type
  base/bucket.go
  base/bucket_gocb.go
Labels: in progress, review

#3624 #3579 Add SetUpTestLogging to setup and teardown logging in tests
  base/bucket_gocb_test.go
  base/log_keys.go
  base/log_keys_test.go
  base/logging.go
  base/util_testing.go
  db/change_cache_test.go
  db/changes_test.go
  db/channel_cache_test.go
  db/database_test.go
  db/event_manager_test.go
  db/import_test.go
  db/kv_dense_channel_storage_test.go
  db/repair_bucket_test.go
  db/revtree_test.go
  db/shadower_test.go
  rest/admin_api_test.go
  rest/api_benchmark_test.go
  rest/api_test.go
  rest/blip_api_test.go
  rest/changes_api_test.go
  rest/utilities_testing.go
Labels: in progress, review

#3638 Attempt to find gozip relative to sgcollect_info before falling back to $PATH
  tools/tasks.py
Labels: P1: high, in progress, review

#3640 Skip long running tests under -short
  db/change_cache_test.go
  db/changes_test.go
  db/database_test.go
  rest/admin_api_test.go
  rest/api_test.go
  rest/api_test_no_race_test.go
  rest/blip_api_test.go
  rest/changes_api_test.go
Labels: in progress, review

#3639 Rename localhost:4985 to myhost:4985 in TestDocumentChangeReplicate
  rest/admin_api_test.go
Labels: in progress, review

#3644 Merge Dev -> Master
  Dockerfile
  base/bucket_gocb_test.go
  base/bucket_n1ql.go
  base/constants.go
  base/log_keys.go
  base/log_keys_test.go
  base/logger_console.go
  base/logger_file.go
  base/logging.go
  base/logging_config.go
  base/logging_test.go
  base/util.go
  base/util_test.go
  base/util_testing.go
  db/change_cache.go
  db/change_cache_test.go
  db/change_index.go
  db/changes_test.go
  db/channel_cache_test.go
  db/database.go
  db/database_test.go
  db/event_manager_test.go
  db/import_test.go
  db/kv_change_index.go
  db/kv_dense_channel_storage_test.go
  db/repair_bucket_test.go
  db/revtree_test.go
  db/shadower_test.go
  db/util_testing.go
  rest/admin_api_test.go
  rest/api_benchmark_test.go
  rest/api_test.go
  rest/blip_api_test.go
  rest/changes_api_test.go
  rest/config.go
  rest/handler.go
  rest/utilities_testing.go
  rest/view_api_test.go
  tools/password_remover.py
  tools/sgcollect_info
  tools/tasks.py
Labels: in progress, review

#3637 MB-29889 Added gozip tool
  build/windows/sgw_windows_build.bat
  manifest/default.xml
Labels: review

#3648 Try to look for gozip in the tools directory, before falling back to …
  tools/tasks.py
Labels: in progress, review

#3646 Port #3637 to release/2.1.0
  build/windows/sgw_windows_build.bat
  manifest/default.xml
Labels: in progress, review

#3647 Update 2.1.0 manifest w/ gozip change.
  manifest/2.1.0.xml
Labels: in progress, review

#3645 Bump version to match version building on master
  base/version.go
Labels: in progress, review

#3649 Bump accel manifest
  manifest/default.xml
Labels: in progress, review

#3661 Fix TLS support for DCP when certpath not specified
  base/bucket.go
Labels: in progress, review

#3663 Fix target branch variable for coveralls
  Jenkinsfile
Labels: in progress, review

#3662 Collate high-volume logs for improved throughput
  base/logger.go
  base/logger_console.go
  base/logger_file.go
  base/logging.go
  base/logging_config.go
  main.go
  rest/config.go
Labels: in progress, review

#3665 Ensure checkpoint data is loaded regardless of backfill status
  base/dcp_feed.go
Labels: in progress, review

#3666 Ensure checkpoint data is loaded regardless of backfill status
  base/dcp_feed.go
Labels: in progress, review

#3668 Flush log buffer before exiting when calling Fatalf()
  base/logging.go
Labels: in progress, review
