Repository couchbase/sync_gateway, pull requests merged in 2018-03, with the labels that each got.

#3348 Retry handling for waitForViewIndexing
  db/design_doc.go
Labels: review

#3349 Improves situation on LiteCore #437
  rest/blip_sync.go
Labels: review

#3347 Feature/issue 3344 view panic
  base/bucket_gocb.go
  base/bucket_gocb_test.go
  base/util.go
  rest/utilities_testing.go
  rest/view_api_test.go
Labels: review

#3362 Bump go-blip in manifest
  manifest/default.xml
Labels: review

#3366 Improve diagnostics for failed non-winning doc unmarshal
  db/document.go
Labels: review

#3367 Add N1QL Create Index, Drop Index, Query
  base/bucket_gocb.go
  base/bucket_n1ql.go
  base/bucket_n1ql_test.go
Labels: review

#3371 #3370 Log Redaction: Stub other redaction types
  base/redactor_metadata.go
  base/redactor_systemdata.go
Labels: review

#3382 Update comments regarding Options.OldRevExpirySeconds
  db/revision.go
Labels: in progress, review

#3378 Remove access related warnings. No longer used
  rest/server_context.go
  rest/server_context_test.go
Labels: in progress, review

#3386 Log Redaction: Change fallback formatting to %+v
  base/redactor_metadata.go
  base/redactor_systemdata.go
  base/redactor_userdata.go
Labels: in progress, review

#3374 asciidoc docs
  docs/antora.yml
  docs/modules/ROOT/_attributes.adoc
  docs/modules/ROOT/assets/images/admin-ui-getting-started.png
  docs/modules/ROOT/assets/images/windows-installation-complete.png
  docs/modules/ROOT/pages/_attributes.adoc
  docs/modules/ROOT/pages/installation.adoc
Labels: review

#3390 Go 1.10: Fix formatting directive in bucket_n1ql_test.go
  base/bucket_n1ql_test.go
Labels: in progress, review

#3380 Logging: #3365 Add new Log Keys implementation
  base/log_keys.go
  base/log_keys_test.go
Labels: in progress, review

#3396 Unmarshal full metadata when checking for upgrade
  db/crud.go
Labels: in progress, review

#3392 Redact for channels package
  channels/change_log.go
  channels/sync_runner.go
Labels: in progress, review

#3398 Fixe #3397 Rename DatabaseContext.tapListener -> DatabaseContext.muta…
  db/assimilator.go
  db/change_cache_test.go
  db/changes.go
  db/database.go
  db/index_changes.go
Labels: in progress, review

#3379 Feature/issue 3313 redact rest
  base/logging.go
  rest/admin_api.go
  rest/api.go
  rest/blip_sync.go
  rest/blip_sync_messages.go
  rest/bulk_api.go
  rest/changes_api.go
  rest/config.go
  rest/handler.go
  rest/oidc_api.go
  rest/server_context.go
  rest/user_agent_version.go
  rest/utilities_testing.go
  rest/view_api.go
Labels: in progress, review

#3391 Feature/issue 3313 log redact db package
  db/assimilator.go
  db/attachment.go
  db/change_cache.go
  db/change_listener.go
  db/changes.go
  db/changes_view.go
  db/channel_cache.go
  db/crud.go
  db/database.go
  db/database_test.go
  db/design_doc.go
  db/document.go
  db/event.go
  db/event_handler.go
  db/event_manager.go
  db/import.go
  db/index_changes.go
  db/kv_change_index.go
  db/kv_change_index_reader.go
  db/kv_channel_index.go
  db/kv_channel_storage.go
  db/kv_dense_block.go
  db/kv_dense_channel_storage.go
  db/kv_dense_channel_storage_reader.go
  db/repair_bucket.go
  db/revision.go
  db/revtree.go
  db/sequence_allocator.go
  db/sequence_hasher.go
  db/sequence_id.go
  db/shadower.go
Labels: in progress, review

#3401 Log Redaction: Use clog for tagging redacted data types
  base/redactor_metadata.go
  base/redactor_systemdata.go
  base/redactor_userdata.go
  base/redactor_userdata_test.go
  manifest/default.xml
Labels: in progress

#3402 Add length check to bodyBytes before unmarshalling
  db/document.go
Labels: in progress, review

#3399 Log Redaction: #3297 auth log redaction
  auth/auth.go
  auth/oidc.go
  auth/user.go
Labels: in progress, review
