Repository couchbase/sync_gateway, pull requests merged in 2018-04, with the labels that each got.

#3400 Install and config for GSI indexes
  base/bucket_n1ql.go
  base/bucket_n1ql_test.go
  db/database.go
  db/database_test.go
  db/design_doc.go
  db/indexes.go
  db/indexes_test.go
  rest/config.go
  rest/server_context.go
Labels: in progress, review

#3412 Fixes #3411 Convert CouchbaseBucketGoCB method receivers to pointer r…
  base/bucket.go
  base/bucket_gocb.go
  base/util.go
  db/channel_index_test.go
  db/database_test.go
Labels: in progress

#3420 Fixes #3404 Create 2.0 branch, switch master to 2.1
  manifest/2.0.0.xml
  manifest/default.xml
  manifest/product-config.json
Labels: in progress, review

#3421 Force build infrastructure to reset build numbers on 2.1.0 builds
  manifest/product-config.json
Labels: in progress, review

#3417 Support using either GSI or Views for queries
  auth/auth.go
  base/bucket.go
  base/bucket_gocb.go
  base/bucket_n1ql.go
  base/bucket_n1ql_test.go
  base/error.go
  base/leaky_bucket.go
  base/logging_bucket.go
  base/stats_bucket.go
  base/util.go
  base/util_testing.go
  db/change_index.go
  db/changes_view.go
  db/crud.go
  db/database.go
  db/database_test.go
  db/design_doc.go
  db/indexes.go
  db/indexes_test.go
  db/query.go
  db/repair_bucket_test.go
  manifest/default.xml
  rest/api.go
  rest/bulk_api.go
  rest/changes_api_test.go
  rest/server_context.go
  rest/utilities_testing.go
Labels: in progress, review

#3405 Remove version from readme.txt
  build/README.txt
Labels: in progress, review

#3431 Locked build repo down to release sha for 2.0.0.xml
  manifest/2.0.0.xml
Labels: in progress, review

#3434 Quote bucket name and index name during creation, readiness query
  base/bucket_n1ql.go
  base/bucket_n1ql_test.go
  db/indexes.go
Labels: in progress, review

#3430 Log Redaction: Tag data in base package for redaction
  base/bucket.go
  base/bucket_gocb.go
  base/bucket_n1ql.go
  base/dcp_feed.go
  base/http_listener.go
  base/logging_bucket.go
  base/redactor.go
  base/replicator.go
  base/rlimit.go
  base/sequence_clock.go
  base/sharded_sequence_clock.go
  base/util.go
  base/util_testing.go
Labels: in progress, review

#3440 Update indexes.go
  db/indexes.go
Labels: in progress, review

#3441 Feature/issue 3364 bucket shadow unsupported
  rest/config.go
  rest/server_context.go
Labels: in progress, review

#3277 Add requireAdmin() to Sync Function (Fixes #3276)
  channels/sync_runner.go
  channels/sync_runner_test.go
Labels: review

#3449 Enforce server version when using GSI
  base/bucket.go
  base/util.go
  base/util_test.go
  rest/server_context.go
Labels: in progress, review

#3451 Restores fatal error handling
  rest/config.go
Labels: in progress, review

#3443 Fixes #2854 remove legacy import
  db/assimilator.go
  db/database.go
  manifest/default.xml
  rest/config.go
  rest/import_test.go
  rest/server_context.go
Labels: in progress

#3444 Include body hash check when identifying SG writes
  base/bucket_gocb.go
  base/bucket_gocb_test.go
  base/util.go
  db/change_cache.go
  db/crud.go
  db/document.go
  db/import.go
  rest/import_test.go
Labels: in progress, review

#3455 Update example configs for new logging
  examples/basic-couchbase-bucket.json
  examples/basic-sync-function.json
  examples/basic-walrus-bucket.json
  examples/basic-walrus-persisted-bucket.json
  examples/basic_sg_accel_config.json
  examples/config-dcpshard.json
  examples/config-server.json
  examples/cors.json
  examples/democlusterconfig.json
  examples/events_webhook.json
  examples/logging-with-rotation.json
  examples/openid-connect.json
  examples/read-write-timeouts.json
  examples/replications-in-config.json
  examples/serviceconfig.json
  examples/ssl/ssl.json
  examples/sync_gateway_with_accel_config.json
  examples/users-roles.json
Labels: in progress, review

#3453 Fix handling of constant in expiry() (Fixes #3452)
  base/util.go
  base/util_test.go
  channels/channelmapper_test.go
Labels: in progress, review

#3461 Check if a LoggingBucket can have indexes created too
  base/logging_bucket.go
  db/indexes.go
Labels: in progress, review

#3463 #3456 Add support for zero meaning disabled in the log rotation maxAge field
  base/logger_file.go
Labels: in progress

#3460 Logging: Another pass of finding old logs
  base/logging.go
  base/logging_bucket.go
  db/attachment.go
  db/change_cache_test.go
  db/change_index.go
  db/database.go
  db/design_doc.go
  db/indexes.go
  db/kv_channel_storage.go
  db/kv_dense_block.go
  db/query.go
  db/revtree.go
  db/shadower.go
  db/shadower_test.go
  main.go
  rest/api.go
  rest/blip_sync.go
  rest/changes_api.go
  rest/config.go
  rest/encoded_response_writer.go
  rest/handler.go
  rest/oidc_api.go
  rest/server_context.go
  rest/view_api.go
Labels: in progress, review

#3465 Move HTTP response logging back to debug
  rest/handler.go
Labels: in progress, review

#3469 #3448 Add --defaultLogFilePath flag to set fallback logFilePath
  base/logging_config.go
  rest/config.go
  service/script_templates/com.couchbase.mobile.sync_gateway.plist
  service/script_templates/systemd_debian_sync_gateway.tpl
  service/script_templates/systemd_sync_gateway.tpl
  service/script_templates/sysv_sync_gateway.tpl
  service/script_templates/upstart_redhat_sync_gateway.tpl
  service/script_templates/upstart_ubuntu_sync_gateway.tpl
  service/sg-windows/sg-service/sg-service.go
Labels: in progress, review

#3468 Fix caller names for Fatalf and Panicf
  base/logging.go
Labels: in progress, review

#3474 Fix for version number, num_replica startup behaviour
  base/version.go
  db/indexes.go
Labels: in progress, review

#3477 Centralize casting to gocbBucket
  base/bucket_gocb.go
  db/database.go
  db/import.go
  db/import_test.go
  db/indexes.go
  db/query.go
  db/sequence_allocator.go
  rest/api_test.go
  rest/import_test.go
Labels: in progress, review

#3459 Refactor event.Sequence -> event.Cas
  base/bucket.go
  base/dcp_feed.go
  base/leaky_bucket.go
  base/leaky_bucket_test.go
  db/shadower.go
  manifest/default.xml
Labels: in progress, review

#3333 Attempt to make gocb bucket flushable
  base/bucket_gocb.go
  base/util_testing.go
  db/database.go
  rest/api.go
  rest/server_context.go
Labels: in progress

#3476 Use deferred build when initializing Sync Gateway indexes
  base/bucket_n1ql.go
  base/bucket_n1ql_test.go
  db/indexes.go
Labels: in progress, review

#3467 #3464 Override log level to debug if we see any + log key
  base/log_keys.go
Labels: in progress

#3483 #3436 Add support to _logging endpoints for new logging
  base/log_keys.go
  base/logging.go
  db/channel_cache_test.go
  db/database_test.go
  rest/admin_api.go
  rest/admin_api_test.go
  rest/api_benchmark_test.go
  rest/config.go
Labels: in progress, review

#3466 Stats and slow query logging for view, n1ql queries
  base/bucket_n1ql.go
  base/bucket_n1ql_test.go
  db/query.go
  db/query_test.go
  rest/config.go
  rest/server_context.go
Labels: in progress, review

#3486 Re-enable vbucket-based test
  db/database_test.go
Labels: in progress, review

#3354 #3296 Add log redaction to sgcollect_info
  tools/cbcollect_info
  tools/sgcollect_info
  tools/tasks.py
Labels: in progress, review

#3480 Feature/issue 3458 pkgerr log redact
  auth/auth.go
  auth/oidc.go
  auth/oidc_provider.go
  base/bucket.go
  base/bucket_gocb.go
  base/bucket_n1ql.go
  base/dcp_feed.go
  base/redactable_error.go
  base/redactor.go
  base/util.go
  channels/sync_runner.go
  db/attachment.go
  db/crud.go
  db/database.go
  db/design_doc.go
  db/document.go
  db/import.go
  db/indexes.go
  rest/config.go
  rest/server_context.go
Labels: in progress, review

#3492 Preserve gocb error types
  base/bucket_gocb.go
Labels: in progress, review

#3494 Logging: Restore defaultMaxSize to 100MB
  base/logger_file.go
Labels: in progress, review

#3487 #3478 Add console-only trace log level
  base/dcp_feed.go
  base/log_level.go
  base/log_level_test.go
  base/logging.go
  base/logging_bucket.go
Labels: in progress, review

#3497 sgcollect_info support for 2.1 logging
  tools/sgcollect_info
  tools/tasks.py
Labels: in progress, review

#3496 Fix logging bucket infinite loop in GetStatsVbSeqno
  base/logging_bucket.go
Labels: in progress, review

#3498 Detect and handle index creation races
  base/bucket_n1ql.go
  base/bucket_n1ql_test.go
  base/error.go
  db/indexes.go
Labels: in progress, review

#3502 Fix for build index error
  base/bucket_gocb.go
  db/database_test.go
  db/indexes.go
  db/indexes_test.go
Labels: in progress, review

#3503 #3470 HTTPResp log key
  base/log_keys.go
  base/log_keys_test.go
  rest/handler.go
Labels: in progress

#3504 #3501 Fix _logging endpoint errors, add unit test, and improve error handling
  rest/admin_api.go
  rest/admin_api_test.go
Labels: in progress

#3507 Enforce views when using accel
  rest/server_context.go
Labels: in progress, review

#3505 Remove num_replicas_housekeeping
  db/database_test.go
  db/indexes.go
  db/indexes_test.go
  rest/config.go
  rest/server_context.go
Labels: in progress, review

#3515 Feature/issue 3385 blip serial num padding
  rest/blip_sync.go
Labels: in progress, review

#3513 Feature/issue 3314 bucket ttl warning
  base/bucket_gocb.go
  base/bucket_gocb_test.go
  db/database.go
Labels: in progress, review

#3512 Fixes #3508 Allow configuration of GoCB opTimeout value
  base/bucket.go
  base/bucket_gocb.go
  rest/config.go
  rest/server_context.go
Labels: in progress

#3517 #3355 Redact configs in sgcollect_info
  tools/password_remover.py
  tools/sgcollect_info
Labels: in progress
