Repository couchbase/sync_gateway, pull requests merged in 2018-05, with the labels that each got.

#3525 Exit sgcollect_info early if SG is not running
  tools/sgcollect_info
Labels: in progress, review

#3528 #3526 sgcollect_info continue even if sg is unreachable
  tools/password_remover.py
  tools/sgcollect_info
Labels: in progress, review

#3524 Add log keys from accel
  base/log_keys.go
  base/sharded_sequence_clock.go
  db/kv_change_index_reader.go
  db/kv_channel_index.go
  db/kv_channel_storage.go
  db/sequence_hasher.go
  manifest/default.xml
Labels: in progress, review

#3535 #3533 Incorrect redaction tags
  base/logging_bucket.go
  db/change_listener.go
  db/database.go
  db/indexes.go
  db/kv_change_index_reader.go
  rest/admin_api.go
  rest/blip_sync.go
  rest/changes_api.go
  rest/config.go
  rest/handler.go
  rest/server_context.go
  rest/view_api.go
Labels: in progress, review

#3540 Fix ordering in star channel index/queries
  db/changes_view.go
  db/database.go
  db/database_test.go
  db/indexes.go
  db/query.go
  rest/api.go
  rest/api_test.go
  rest/changes_api_test.go
Labels: in progress, review

#3516 Feature/issue sg 3445 sync fn mutations
  manifest/default.xml
  rest/routing.go
Labels: in progress, review

#3552 Handle SIGHUP and rotate log files
  base/logger_file.go
  base/logging.go
  main.go
  rest/config.go
Labels: in progress, review

#3550 #3549 Change _sgcollect_info endpoint zip filename format for Windows compatibility
  base/util.go
  base/util_test.go
  rest/admin_api.go
  rest/sgcollect.go
  rest/sgcollect_test.go
Labels: in progress, review

#3564 #3561 Improve sgcollect error messages for s3 upload
  rest/sgcollect.go
  tools/tasks.py
Labels: in progress, review

#3538 #3537 Redact path variables in URL logging
  base/logging.go
  base/util.go
  base/util_test.go
  rest/api.go
  rest/bulk_api.go
  rest/handler.go
  rest/handler_test.go
  rest/ioutil.go
  rest/routing.go
  rest/server_context.go
Labels: in progress, review

#3573 #3572 Fixes sgcollect_info bad request if upload_host is unset
  rest/sgcollect.go
Labels: in progress, review

#3568 Support for x.509 authentication
  base/bucket.go
  base/bucket_gocb.go
  base/bucket_test.go
  base/dcp_feed.go
  base/util.go
  db/channel_index_test.go
  db/database.go
  manifest/default.xml
  rest/config.go
  rest/server_context.go
Labels: in progress, review

#3565 #3536 #3529 Remove old logging and consolidate log keys
  auth/auth.go
  auth/oidc.go
  base/bucket.go
  base/bucket_gocb_test.go
  base/bucket_n1ql.go
  base/dcp_feed.go
  base/log_keys.go
  base/logging.go
  base/util_testing.go
  db/assimilator.go
  db/attachment.go
  db/change_cache.go
  db/change_cache_test.go
  db/change_listener.go
  db/changes.go
  db/changes_test.go
  db/channel_cache_test.go
  db/database.go
  db/database_test.go
  db/event_handler.go
  db/import_test.go
  db/indexes.go
  db/kv_channel_index.go
  db/kv_dense_block.go
  db/kv_dense_channel_storage.go
  db/kv_dense_channel_storage_reader.go
  db/kv_dense_channel_storage_test.go
  db/repair_bucket_test.go
  db/revtree_test.go
  manifest/default.xml
  rest/admin_api_test.go
  rest/api_test.go
  rest/changes_api.go
  rest/changes_api_test.go
  rest/config.go
  rest/handler.go
  rest/oidc_api.go
  rest/oidc_test_provider.go
  rest/utilities_testing.go
Labels: review

#3577 #3574 Add tests for sgCollectOptions functions (Validate and Args)
  base/util_testing.go
  rest/sgcollect_test.go
Labels: in progress, review

#3576 #3566 Optimise URL sanitization by copying value of URL.Query()
  base/logging.go
  base/util.go
  base/util_test.go
  rest/handler.go
  rest/ioutil.go
Labels: in progress, review

#3599 Merge master -> dev
  db/channel_cache.go
  db/channel_cache_test.go
Labels: in progress, review

#3593 Improve error reporting in CouchbaseBucketGoCB.Query()
  base/bucket_n1ql.go
  base/constants.go
  rest/handler.go
Labels: in progress, review

#3527 Fix Python lint issues for sgcollect_info, tasks.py, password_remover.py
  tools/password_remover.py
  tools/sgcollect_info
  tools/tasks.py
Labels: in progress, review

#3607 Fixes issue #3558 Initialize cache after DCP start
  db/change_cache.go
  db/change_cache_test.go
  db/change_index.go
  db/database.go
  db/kv_change_index.go
  db/util_testing.go
Labels: in progress, review

#3520 Feature/issue 3481 2nd testbucket settings
  base/util.go
  base/util_test.go
  base/util_testing.go
  rest/api_test.go
  rest/config.go
Labels: in progress, review

#3616 #3614 Logging performance optimisations
  base/logger_console_test.go
  base/logger_file.go
  base/logger_file_test.go
  base/logging.go
  base/logging_test.go
Labels: in progress

#3591 #3587 #3597 fix default windows output_dir, make validation rules stricter, improve logging
  rest/admin_api.go
  rest/sgcollect.go
  rest/sgcollect_test.go
Labels: P2: medium, in progress, review

#3603 Move RedactBasicAuthURL into base so it can be used by SG Accel
  base/util.go
  base/util_test.go
  db/event_handler.go
  manifest/default.xml
Labels: P1: high, review
